In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline


In [ ]:
# x is m x n
# y is m x 1
# a is m x 1
# z is m x 1
# a = sigmoid (z)
# w is n x 1
# b is a number
# initialize w to matrix of n x 1
# x.T is n x m
# z=np.dot(x,w)+b
# x[i] is (n,) need to be reshaped 
# np.dot(x[i],w) +b gives a[i]
# dz = a-y (m x 1)
# dw[i]+=dz[j]*x[j][i]...dw[i]=(1/m)*dw[i]
# dw=(1/m)*np.dot(x.T,dz)
# db=(1/m)*np.sum(dz)

# dw is n x 1


In [2]:
a=np.array([[1,2,3,4],[5,6,7,8],[2,4,6,8]])

In [3]:
b=np.array([[1],[2],[3]])

In [8]:
a*b

array([[ 1,  2,  3,  4],
       [10, 12, 14, 16],
       [ 6, 12, 18, 24]])

In [9]:
c=np.array([[2],[3],[4],[5]])

In [11]:
c.shape


(4, 1)

In [13]:
a/c.reshape(1,4)

array([[0.5       , 0.66666667, 0.75      , 0.8       ],
       [2.5       , 2.        , 1.75      , 1.6       ],
       [1.        , 1.33333333, 1.5       , 1.6       ]])

In [19]:
(a.T/c).T

array([[0.5       , 0.66666667, 0.75      , 0.8       ],
       [2.5       , 2.        , 1.75      , 1.6       ],
       [1.        , 1.33333333, 1.5       , 1.6       ]])

In [21]:
a.sum(axis=0)

array([ 8, 12, 16, 20])

In [22]:
a.shape

(3, 4)

In [25]:
c.shape

(1, 4)

In [24]:
c=c.T

In [26]:
a+c

array([[ 3,  5,  7,  9],
       [ 7,  9, 11, 13],
       [ 4,  7, 10, 13]])

In [27]:
a


array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [2, 4, 6, 8]])

In [28]:
c

array([[2, 3, 4, 5]])