In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df=pd.read_csv("Bengaluru_House_Data_edited.csv")

In [3]:
df

area_type   availability                  location       size  \
0    Super built-up  Area         19-Dec  Electronic City Phase II      2 BHK   
1              Plot  Area  Ready To Move          Chikka Tirupathi  4 Bedroom   
2          Built-up  Area  Ready To Move               Uttarahalli      3 BHK   
3    Super built-up  Area  Ready To Move        Lingadheeranahalli      3 BHK   
4    Super built-up  Area  Ready To Move                  Kothanur      2 BHK   
..                    ...            ...                       ...        ...   
990  Super built-up  Area         19-Jan               Mysore Road      2 BHK   
991        Built-up  Area  Ready To Move                     Hoodi      2 BHK   
992            Plot  Area  Ready To Move             Chikkabanavar  1 Bedroom   
993            Plot  Area         18-Aug                      ITPL  3 Bedroom   
994        Built-up  Area  Ready To Move         Somasundara Palya      2 BHK   

     society total_sqft  bath  balcony   price  
0    Coomee        1056   2.0      1.0   39.07  
1    Theanmp       2600   5.0      3.0  120.00  
2        NaN       1440   2.0      3.0   62.00  
3    Soiewre       1521   3.0      1.0   95.00  
4        NaN       1200   2.0      1.0   51.00  
..       ...        ...   ...      ...     ...  
990      NaN       1175   2.0      1.0   73.50  
991  Goeur G       1425   2.0      2.0   80.00  
992      NaN       1200   1.0      0.0   20.00  
993      NaN       1200   3.0      1.0   56.12  
994  Abeesmi       1255   2.0      2.0   67.00  

[995 rows x 9 columns]

In [4]:
df.dropna(inplace =True)

In [5]:
df.reset_index(inplace=True)

In [6]:
df

index             area_type   availability                  location  \
0        0  Super built-up  Area         19-Dec  Electronic City Phase II   
1        1            Plot  Area  Ready To Move          Chikka Tirupathi   
2        3  Super built-up  Area  Ready To Move        Lingadheeranahalli   
3        5  Super built-up  Area  Ready To Move                Whitefield   
4       11            Plot  Area  Ready To Move                Whitefield   
..     ...                   ...            ...                       ...   
572    985  Super built-up  Area         18-Jul                 Hosa Road   
573    986  Super built-up  Area  Ready To Move                  Sarjapur   
574    989  Super built-up  Area  Ready To Move              Yeshwanthpur   
575    991        Built-up  Area  Ready To Move                     Hoodi   
576    994        Built-up  Area  Ready To Move         Somasundara Palya   

          size  society total_sqft  bath  balcony    price  
0        2 BHK  Coomee        1056   2.0      1.0   39.070  
1    4 Bedroom  Theanmp       2600   5.0      3.0  120.000  
2        3 BHK  Soiewre       1521   3.0      1.0   95.000  
3        2 BHK  DuenaTa       1170   2.0      1.0   38.000  
4    4 Bedroom  Prrry M       2785   5.0      3.0  295.000  
..         ...      ...        ...   ...      ...      ...  
572      2 BHK  Mahesr        1161   2.0      1.0   55.150  
573      1 BHK  DSousyl        645   1.0      0.0   17.535  
574      1 BHK  IBityin        665   1.0      1.0   36.850  
575      2 BHK  Goeur G       1425   2.0      2.0   80.000  
576      2 BHK  Abeesmi       1255   2.0      2.0   67.000  

[577 rows x 10 columns]

In [7]:
df.drop("index",axis=1,inplace =True)

In [8]:
house=pd.DataFrame()

In [9]:
house['x0']=[1 for i in range(0,len(df))]

In [12]:
house['bath']=df['bath']

In [13]:
house['balcony']=df["balcony"]

In [22]:
house['sqrt_size']=[int(i[0])**0.5 for i in df["size"]]

In [15]:
house

x0  bath  balcony  size
0     1   2.0      1.0     2
1     1   5.0      3.0     4
2     1   3.0      1.0     3
3     1   2.0      1.0     2
4     1   5.0      3.0     4
..   ..   ...      ...   ...
572   1   2.0      1.0     2
573   1   1.0      0.0     1
574   1   1.0      1.0     1
575   1   2.0      2.0     2
576   1   2.0      2.0     2

[577 rows x 4 columns]

In [24]:
house["total_sqft"]=[float(i[0:i.find(" ")])/1000 if '-' in i else float(i)/1000 for i in df["total_sqft"]]

In [25]:
house

x0  bath  balcony  sqrt_size  total_sqft
0     1   2.0      1.0   1.414214       1.056
1     1   5.0      3.0   2.000000       2.600
2     1   3.0      1.0   1.732051       1.521
3     1   2.0      1.0   1.414214       1.170
4     1   5.0      3.0   2.000000       2.785
..   ..   ...      ...        ...         ...
572   1   2.0      1.0   1.414214       1.161
573   1   1.0      0.0   1.000000       0.645
574   1   1.0      1.0   1.000000       0.665
575   1   2.0      2.0   1.414214       1.425
576   1   2.0      2.0   1.414214       1.255

[577 rows x 5 columns]

In [23]:
house.drop(["size",'total_sqft'],axis=1,inplace=True)

In [30]:
house["sq_total_sqft"]=(np.array(house["total_sqft"])**2)

In [31]:
house["cube_total_sqft"]=(np.array(house["total_sqft"])**3)

In [32]:
house

x0  bath  balcony  sqrt_size  total_sqft  sq_total_sqft  cube_total_sqft
0     1   2.0      1.0   1.414214       1.056       1.115136         1.177584
1     1   5.0      3.0   2.000000       2.600       6.760000        17.576000
2     1   3.0      1.0   1.732051       1.521       2.313441         3.518744
3     1   2.0      1.0   1.414214       1.170       1.368900         1.601613
4     1   5.0      3.0   2.000000       2.785       7.756225        21.601087
..   ..   ...      ...        ...         ...            ...              ...
572   1   2.0      1.0   1.414214       1.161       1.347921         1.564936
573   1   1.0      0.0   1.000000       0.645       0.416025         0.268336
574   1   1.0      1.0   1.000000       0.665       0.442225         0.294080
575   1   2.0      2.0   1.414214       1.425       2.030625         2.893641
576   1   2.0      2.0   1.414214       1.255       1.575025         1.976656

[577 rows x 7 columns]

In [33]:
def costfun(X,y,theta):
    j=0
    m,n=X.shape
    for i in range(0,m):
        j=j+((np.matmul(theta.T,X[i].reshape(n,1))-y[i])**2)/(2*m)
    return j

In [64]:
def diffarray(X,y,theta):
    m,n=X.shape
    list1=[]
    for j in range(0,n):
        x=0
        for i in range(0,m):
            x=x+((np.matmul(theta.T,X[i].reshape(n,1))-y[i])*X[i][j])/m
        list1.append(x)
#     print("derivative",np.array(list1).reshape(n,1))
    return np.array(list1).reshape(n,1)

In [104]:
def gradientdescent(X,y):
    m,n=X.shape
    a=0.1
    theta=np.array([0 for i in range(0,n)]).reshape(n,1)
    jprev=costfun(X,y,theta)
    jprev=float(jprev)
    print(jprev)
    counter=0
    rel=[]
    while True:
        temp=theta-a*diffarray(X,y,theta)
        theta=temp.reshape(n,1)
#         print("theta",theta)
        j=costfun(X,y,theta)
        j=float(j)
        print(jprev-j)
        
        if jprev-j <= 0.03:
            print("final:",j)
            print("derivative",diffarray(X,y,theta))
            return theta
        else:
            jprev=j
            
     
     
          

In [36]:
X=np.array(house)

In [37]:
Y=np.array(df["price"])

In [41]:
Y=Y.reshape(577,1)


In [76]:
X

array([[ 1.        ,  2.        ,  1.        , ...,  1.056     ,
         1.115136  ,  1.17758362],
       [ 1.        ,  5.        ,  3.        , ...,  2.6       ,
         6.76      , 17.576     ],
       [ 1.        ,  3.        ,  1.        , ...,  1.521     ,
         2.313441  ,  3.51874376],
       ...,
       [ 1.        ,  1.        ,  1.        , ...,  0.665     ,
         0.442225  ,  0.29407963],
       [ 1.        ,  2.        ,  2.        , ...,  1.425     ,
         2.030625  ,  2.89364063],
       [ 1.        ,  2.        ,  2.        , ...,  1.255     ,
         1.575025  ,  1.97665637]])

In [74]:
theta=gradientdescent(X,Y)

7485.434587911612
theta [[9.31736395e-08]
 [2.80211941e-07]
 [1.59174697e-07]
 [1.56659919e-07]
 [1.90280801e-07]
 [7.28336222e-07]
 [1.10683754e-05]]
0.12301678533003724
theta [[1.86346386e-07]
 [5.60421135e-07]
 [3.18346786e-07]
 [3.13318286e-07]
 [3.80532563e-07]
 [1.45566232e-06]
 [2.21014182e-05]]
0.12223564742089366
theta [[2.79518242e-07]
 [8.40627592e-07]
 [4.77516275e-07]
 [4.69975105e-07]
 [5.70755380e-07]
 [2.18198151e-06]
 [3.30992411e-05]]
0.12145948327179212
theta [[3.72689212e-07]
 [1.12083132e-06]
 [6.36683173e-07]
 [6.26630381e-07]
 [7.60949343e-07]
 [2.90729700e-06]
 [4.40619563e-05]]
0.12068826130052912
theta [[4.65859296e-07]
 [1.40103232e-06]
 [7.95847487e-07]
 [7.83284119e-07]
 [9.51114544e-07]
 [3.63161200e-06]
 [5.49896759e-05]]
0.11992194992672012
theta [[5.59028499e-07]
 [1.68123062e-06]
 [9.55009227e-07]
 [9.39936324e-07]
 [1.14125108e-06]
 [4.35492970e-06]
 [6.58825113e-05]]
0.11916051798743865
theta [[6.52196823e-07]
 [1.96142621e-06]
 [1.11416840e-06]
 [1.

theta [[5.30955189e-06]
 [1.59679417e-05]
 [9.06902828e-06]
 [8.92727579e-06]
 [1.08022564e-05]
 [3.99933261e-05]
 [5.77665952e-04]]
0.08612422593068914
theta [[5.40267891e-06]
 [1.62480103e-05]
 [9.22806684e-06]
 [9.08385464e-06]
 [1.09910215e-05]
 [4.06689379e-05]
 [5.86890111e-04]]
0.08557799652498943
theta [[5.49580518e-06]
 [1.65280765e-05]
 [9.38710321e-06]
 [9.24043220e-06]
 [1.11797623e-05]
 [4.13437076e-05]
 [5.96084819e-04]]
0.08503524514617311
theta [[5.58893071e-06]
 [1.68081405e-05]
 [9.54613743e-06]
 [9.39700847e-06]
 [1.13684791e-05]
 [4.20176380e-05]
 [6.05250168e-04]]
0.08449594968260499
theta [[5.68205550e-06]
 [1.70882022e-05]
 [9.70516948e-06]
 [9.55358346e-06]
 [1.15571718e-05]
 [4.26907318e-05]
 [6.14386253e-04]]
0.08396008811178035
theta [[5.77517955e-06]
 [1.73682616e-05]
 [9.86419937e-06]
 [9.71015716e-06]
 [1.17458405e-05]
 [4.33629916e-05]
 [6.23493167e-04]]
0.08342763854579971
theta [[5.86830287e-06]
 [1.76483187e-05]
 [1.00232271e-05]
 [9.86672958e-06]
 [1.

theta [[1.03374015e-05]
 [3.10885379e-05]
 [1.76541632e-05]
 [1.73807790e-05]
 [2.09627710e-05]
 [7.53354282e-05]
 [1.03586268e-03]]
0.061097506162695936
theta [[1.04304915e-05]
 [3.13684926e-05]
 [1.78130937e-05]
 [1.75372935e-05]
 [2.11503335e-05]
 [7.59692099e-05]
 [1.04362369e-03]]
0.0607106311026655
theta [[1.05235809e-05]
 [3.16484454e-05]
 [1.79720224e-05]
 [1.76938069e-05]
 [2.13378757e-05]
 [7.66022830e-05]
 [1.05135993e-03]]
0.0603262193953924
theta [[1.06166696e-05]
 [3.19283962e-05]
 [1.81309492e-05]
 [1.78503192e-05]
 [2.15253975e-05]
 [7.72346498e-05]
 [1.05907145e-03]]
0.05994425539392978
theta [[1.07097577e-05]
 [3.22083451e-05]
 [1.82898742e-05]
 [1.80068305e-05]
 [2.17128991e-05]
 [7.78663125e-05]
 [1.06675834e-03]]
0.05956472346861119
theta [[1.08028453e-05]
 [3.24882921e-05]
 [1.84487975e-05]
 [1.81633406e-05]
 [2.19003806e-05]
 [7.84972733e-05]
 [1.07442069e-03]]
0.05918760818985902
theta [[1.08959322e-05]
 [3.27682373e-05]
 [1.86077189e-05]
 [1.83198497e-05]
 [2.2

theta [[1.53634118e-05]
 [4.62034769e-05]
 [2.62339292e-05]
 [2.58310843e-05]
 [3.10635424e-05]
 [1.08599449e-04]
 [1.42137175e-03]]
0.04337196089090867
theta [[1.54564707e-05]
 [4.64833357e-05]
 [2.63927687e-05]
 [2.59875446e-05]
 [3.12500928e-05]
 [1.09198027e-04]
 [1.42790140e-03]]
0.043097950860101264
theta [[1.55495290e-05]
 [4.67631929e-05]
 [2.65516067e-05]
 [2.61440040e-05]
 [3.14366261e-05]
 [1.09796009e-04]
 [1.43441020e-03]]
0.04282568558846833
theta [[1.56425868e-05]
 [4.70430485e-05]
 [2.67104432e-05]
 [2.63004625e-05]
 [3.16231423e-05]
 [1.10393396e-04]
 [1.44089821e-03]]
0.04255515390741493
theta [[1.57356440e-05]
 [4.73229025e-05]
 [2.68692781e-05]
 [2.64569201e-05]
 [3.18096415e-05]
 [1.10990191e-04]
 [1.44736549e-03]]
0.0422863448084172
theta [[1.58287007e-05]
 [4.76027548e-05]
 [2.70281115e-05]
 [2.66133767e-05]
 [3.19961237e-05]
 [1.11586395e-04]
 [1.45381211e-03]]
0.04201924731933104
theta [[1.59217570e-05]
 [4.78826056e-05]
 [2.71869434e-05]
 [2.67698325e-05]
 [3.

theta [[2.05739378e-05]
 [6.18732062e-05]
 [3.51266994e-05]
 [3.45915250e-05]
 [4.14854155e-05]
 [1.41251983e-04]
 [1.75667717e-03]]
0.030430672988586593
theta [[2.06669695e-05]
 [6.21529815e-05]
 [3.52854597e-05]
 [3.47479381e-05]
 [4.16710853e-05]
 [1.41819932e-04]
 [1.76213548e-03]]
0.030239064912166214
theta [[2.07600008e-05]
 [6.24327555e-05]
 [3.54442187e-05]
 [3.49043505e-05]
 [4.18567408e-05]
 [1.42387383e-04]
 [1.76757635e-03]]
0.030048676871047064
theta [[2.08530316e-05]
 [6.27125282e-05]
 [3.56029765e-05]
 [3.50607621e-05]
 [4.20423819e-05]
 [1.42954336e-04]
 [1.77299983e-03]]
0.029859501110877318
theta [[2.09460620e-05]
 [6.29922994e-05]
 [3.57617330e-05]
 [3.52171729e-05]
 [4.22280089e-05]
 [1.43520794e-04]
 [1.77840598e-03]]
0.029671529908227967
theta [[2.10390919e-05]
 [6.32720694e-05]
 [3.59204882e-05]
 [3.53735830e-05]
 [4.24136216e-05]
 [1.44086757e-04]
 [1.78379485e-03]]
0.029484755576049793
theta [[2.11321214e-05]
 [6.35518380e-05]
 [3.60792421e-05]
 [3.55299923e-05

theta [[2.57830692e-05]
 [7.75386461e-05]
 [4.40154012e-05]
 [4.33495410e-05]
 [5.18620590e-05]
 [1.72331417e-04]
 [2.03695863e-03]]
0.021381166989158373
theta [[2.58760782e-05]
 [7.78183516e-05]
 [4.41740953e-05]
 [4.35059146e-05]
 [5.20469924e-05]
 [1.72873753e-04]
 [2.04152105e-03]]
0.02124718046070484
theta [[2.59690868e-05]
 [7.80980559e-05]
 [4.43327883e-05]
 [4.36622876e-05]
 [5.22319138e-05]
 [1.73415672e-04]
 [2.04606889e-03]]
0.021114047052833484
theta [[2.60620950e-05]
 [7.83777591e-05]
 [4.44914802e-05]
 [4.38186600e-05]
 [5.24168232e-05]
 [1.73957176e-04]
 [2.05060219e-03]]
0.020981761362236284
theta [[2.61551029e-05]
 [7.86574612e-05]
 [4.46501710e-05]
 [4.39750317e-05]
 [5.26017207e-05]
 [1.74498265e-04]
 [2.05512099e-03]]
0.020850317992881173
theta [[2.62481104e-05]
 [7.89371622e-05]
 [4.48088608e-05]
 [4.41314027e-05]
 [5.27866063e-05]
 [1.75038941e-04]
 [2.05962535e-03]]
0.020719711560559517
theta [[2.63411175e-05]
 [7.92168620e-05]
 [4.49675495e-05]
 [4.42877731e-05]

theta [[3.09910330e-05]
 [9.32004954e-05]
 [5.29006987e-05]
 [5.21055273e-05]
 [6.22008780e-05]
 [2.02095378e-04]
 [2.27122761e-03]]
0.015053082775011717
theta [[3.10840230e-05]
 [9.34801423e-05]
 [5.30593373e-05]
 [5.22618678e-05]
 [6.23851955e-05]
 [2.02616296e-04]
 [2.27504087e-03]]
0.014959389462092076
theta [[3.11770126e-05]
 [9.37597884e-05]
 [5.32179750e-05]
 [5.24182079e-05]
 [6.25695030e-05]
 [2.03136865e-04]
 [2.27884194e-03]]
0.014866292754959431
theta [[3.12700020e-05]
 [9.40394334e-05]
 [5.33766118e-05]
 [5.25745473e-05]
 [6.27538005e-05]
 [2.03657086e-04]
 [2.28263084e-03]]
0.014773788810089172
theta [[3.13629910e-05]
 [9.43190775e-05]
 [5.35352478e-05]
 [5.27308863e-05]
 [6.29380880e-05]
 [2.04176961e-04]
 [2.28640762e-03]]
0.014681873860354244
theta [[3.14559797e-05]
 [9.45987207e-05]
 [5.36938828e-05]
 [5.28872247e-05]
 [6.31223656e-05]
 [2.04696491e-04]
 [2.29017232e-03]]
0.014590544184102328
theta [[3.15489681e-05]
 [9.48783630e-05]
 [5.38525169e-05]
 [5.30435626e-05

theta [[3.61050449e-05]
 [1.08579739e-04]
 [6.16245541e-05]
 [6.07035007e-05]
 [7.23242539e-05]
 [2.30256000e-04]
 [2.46382275e-03]]
0.010693955084207118
theta [[3.61980192e-05]
 [1.08859338e-04]
 [6.17831471e-05]
 [6.08598141e-05]
 [7.25080647e-05]
 [2.30759300e-04]
 [2.46701977e-03]]
0.010628017950693902
theta [[3.62909933e-05]
 [1.09138936e-04]
 [6.19417393e-05]
 [6.10161269e-05]
 [7.26918672e-05]
 [2.31262307e-04]
 [2.47020656e-03]]
0.010562500646301487
theta [[3.63839670e-05]
 [1.09418533e-04]
 [6.21003308e-05]
 [6.11724393e-05]
 [7.28756612e-05]
 [2.31765023e-04]
 [2.47338315e-03]]
0.01049740052985726
theta [[3.64769405e-05]
 [1.09698130e-04]
 [6.22589215e-05]
 [6.13287513e-05]
 [7.30594469e-05]
 [2.32267448e-04]
 [2.47654957e-03]]
0.010432714920170838
theta [[3.65699138e-05]
 [1.09977725e-04]
 [6.24175115e-05]
 [6.14850628e-05]
 [7.32432243e-05]
 [2.32769583e-04]
 [2.47970586e-03]]
0.010368441209720913
theta [[3.66628868e-05]
 [1.10257320e-04]
 [6.25761007e-05]
 [6.16413739e-05]

In [75]:
theta

array([[3.71277479e-05],
       [1.11655282e-04],
       [6.33690356e-05],
       [6.24229226e-05],
       [7.43457150e-05],
       [2.35776361e-04],
       [2.49843254e-03]])

In [77]:
3.71277479e-05*100000

3.71277479

In [78]:
house["sq_total_sqft"]=np.array(house["sq_total_sqft"])/house['sq_total_sqft'].max()

In [81]:
house["cube_total_sqft"]=np.array(house["cube_total_sqft"])/house['cube_total_sqft'].max()

In [82]:
house

x0  bath  balcony  sqrt_size  total_sqft  sq_total_sqft  cube_total_sqft
0     1   2.0      1.0   1.414214       1.056       0.000910         0.000910
1     1   5.0      3.0   2.000000       2.600       0.005518         0.005518
2     1   3.0      1.0   1.732051       1.521       0.001889         0.001889
3     1   2.0      1.0   1.414214       1.170       0.001117         0.001117
4     1   5.0      3.0   2.000000       2.785       0.006332         0.006332
..   ..   ...      ...        ...         ...            ...              ...
572   1   2.0      1.0   1.414214       1.161       0.001100         0.001100
573   1   1.0      0.0   1.000000       0.645       0.000340         0.000340
574   1   1.0      1.0   1.000000       0.665       0.000361         0.000361
575   1   2.0      2.0   1.414214       1.425       0.001658         0.001658
576   1   2.0      2.0   1.414214       1.255       0.001286         0.001286

[577 rows x 7 columns]

In [100]:
X=np.array(house.drop(['sq_total_sqft','cube_total_sqft'],axis=1).head(50))

In [105]:
theta=gradientdescent(X,Y)

11074.503489
4220.871078570443
2084.7355962456795
1063.477938920868
572.9935238917906
335.35509632914454
218.3085267562592
158.90898824056057
127.18891320930925
108.87202472417312
97.14899821490826
88.76441850211495
82.15494740878307
76.56341257828808
71.61722243719032
67.12770314811655
62.994551599242186
59.1603063857674
55.588622012001
52.25387349176049
49.136156628084336
46.2188599529552
43.48746433576525
40.92893046313725
38.531369462039265
36.28385138483418
34.17628216217963
32.199315759347655
30.344285483123258
28.603146595527278
26.968426314501812
25.433179165265074
23.990946557383154
22.635719909906356
21.361906872292934
20.164300307487906
19.038049770300063
17.9786352554803
16.981843018051222
16.043743289777012
15.160669732769065
14.329200485998967
13.546140673347395
12.808506253326868
12.113509101011005
11.458543222124831
10.841172007771547
10.259116446099483
9.710244214269665
9.192559580568059
8.704194052423986
8.243397711421721
7.80853118138964
7.398058180057092
7.010538608

In [103]:
theta

array([[-16.55662023],
       [  5.0010461 ],
       [-13.50213476],
       [-48.16371727],
       [134.11418756]])

In [101]:
X


array([[1.        , 2.        , 1.        , 1.41421356, 1.056     ],
       [1.        , 5.        , 3.        , 2.        , 2.6       ],
       [1.        , 3.        , 1.        , 1.73205081, 1.521     ],
       [1.        , 2.        , 1.        , 1.41421356, 1.17      ],
       [1.        , 5.        , 3.        , 2.        , 2.785     ],
       [1.        , 2.        , 1.        , 1.41421356, 1.        ],
       [1.        , 3.        , 2.        , 1.73205081, 2.25      ],
       [1.        , 2.        , 2.        , 1.41421356, 1.175     ],
       [1.        , 3.        , 2.        , 1.73205081, 1.18      ],
       [1.        , 3.        , 3.        , 1.73205081, 1.54      ],
       [1.        , 4.        , 2.        , 1.73205081, 2.77      ],
       [1.        , 3.        , 1.        , 1.73205081, 1.755     ],
       [1.        , 5.        , 2.        , 2.        , 2.8       ],
       [1.        , 1.        , 0.        , 1.        , 0.51      ],
       [1.        , 1.        , 1.