In [1]:
import numpy as np

In [2]:
arr=np.array([[1,2],[3,4],[5,6]])

In [7]:
arr.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [22]:
a=np.linalg.pinv(arr)

In [23]:
a

array([[-1.33333333, -0.33333333,  0.66666667],
       [ 1.08333333,  0.33333333, -0.41666667]])

In [5]:
arr[0]

1

In [6]:
arr[3]

4

In [7]:
arr[4]

IndexError: index 4 is out of bounds for axis 0 with size 4

In [8]:
arr[-1]

4

In [9]:
arr[0:-1:2]

array([1, 3])

In [10]:
arr+1

array([2, 3, 4, 5])

In [11]:
arr*2


array([2, 4, 6, 8])

In [12]:
arr%2

array([1, 0, 1, 0], dtype=int32)

In [13]:
arr>2

array([False, False,  True,  True])

In [14]:
arr2=np.array([[1,2,3],[4,5,6]])

In [15]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr2[1]

In [ ]:
arr2[1][2]

In [ ]:
arr[0:2][1]

In [17]:
arr3=np.array((1,2,3))

In [18]:
arr3

array([1, 2, 3])

In [19]:
arr3[2]

3

In [20]:
arr3[1:3]

array([2, 3])

In [21]:
type(arr3)

numpy.ndarray

In [22]:
type(arr3[2])

numpy.int32

In [25]:
arr3.sum() 
#gives sum of all elements in a array

6

In [26]:
arr3+arr2

array([[2, 4, 6],
       [5, 7, 9]])

### 

In [28]:
arr3*arr2

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [29]:
arr2.T


array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
arr4=np.add(arr3,arr2)

In [ ]:
arr4

In [ ]:
sqrt=np.sqrt(arr2)

In [ ]:
sqrt

In [ ]:
sqrt.dtype

In [ ]:
arr2.dtype

In [ ]:
arr2.T

# different methods

In [37]:
np.all([[1,0],[1,0]],axis=0)  # is axis not mentioned checks in all

array([ True, False])

axis=0--->vertical 
=1 --->horizontal
all checks if all along a axis(is mentioned) is true or not
any checks is any one is true  or not

In [38]:
np.arange(1,6)

array([1, 2, 3, 4, 5])

In [39]:
np.arange(1,6,3)

array([1, 4])

In [40]:
arr5=np.arange(1,26)

In [41]:
arr5.reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [42]:
arr6=arr5.reshape(5,5)

In [43]:
arr6

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [44]:
arr6[1:3]

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [45]:
arr6[1:3,1:5]


array([[ 7,  8,  9, 10],
       [12, 13, 14, 15]])

In [46]:
arr6


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [47]:
arr6[0,0]

1

In [48]:
arr6[0][0]

1

In [49]:
arr6[3,3]

19

put funtion--->replaces some values 

In [30]:
arr7=np.arange(0,5)

In [31]:
arr7

array([0, 1, 2, 3, 4])

In [32]:
np.put(arr7,[0,2],[5])

In [33]:
arr7

array([5, 1, 5, 3, 4])

In [34]:
np.put(arr7,[0],[7,2]) # gives no error even if we want to replace only one
# in second argument we have to provide the indexes in a single number

In [35]:
arr7

array([7, 1, 5, 3, 4])

In [50]:
np.put(arr6,[10],[53])

In [51]:
arr6

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [53, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

argmax-->max element index returns
nanargmax-->max element index return ignoring nans

In [52]:
np.argmax(arr6)

10

In [55]:
np.argmax(arr6,axis=0) # along vertical 

array([2, 4, 4, 4, 4], dtype=int64)

INSERT METHOD

In [74]:
arr8=np.arange(0,4)

In [75]:
arr8

array([0, 1, 2, 3])

In [79]:
arr8=np.insert(arr8,[4],[4,3])  # try to run this cell multiple times

In [80]:
arr8

array([0, 1, 2, 3, 4, 3, 4, 3])

In [82]:
arr9=np.array([1.2,2.3,3.4])

In [83]:
np.ceil(arr9) # gint

array([2., 3., 4.])

identity matrix formation

In [ ]:
arr10=np.identity(4)

In [ ]:
arr10

In [ ]:
arr11=np.arange(0,5)

In [ ]:
arr11

In [ ]:
bool1=arr11>2

In [ ]:
bool1

In [ ]:
# arr11(bool1,axis=1)

In [ ]:
# arr12=np.array([1,2],[1,2,3]) ERROR