In [1]:
import numpy as np


In [27]:
X=np.array([[1,2,3,4],[1,3,5,7]])

In [25]:
Y=np.array([[6,7,8,9],[1,2,3,4]])

In [35]:
print(X.shape)
print(Y.shape)
print(np.matmul(Y,X.T))
print(Y.dot(X.T))

(2, 4)
(2, 4)
[[ 80 130]
 [ 30  50]]
[[ 80 130]
 [ 30  50]]


In [22]:
print(X)

[[1 2 3 4]
 [1 3 5 7]]


In [23]:
print(Y)

[[6 7 8 9]
 [1 2 3 4]]


In [32]:
X.T

array([[1, 1],
       [2, 3],
       [3, 5],
       [4, 7]])